services:
  nextjs-app:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_valid_looking_clerk_key_for_build_12345
        - CLERK_SECRET_KEY=sk_test_valid_looking_clerk_secret_key_for_build_67890
        - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
        - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
        - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
        - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/character/select
        - NEXT_PUBLIC_CLERK_MOCK_MODE=true
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_valid_looking_clerk_key_for_build_12345
      - CLERK_SECRET_KEY=sk_test_valid_looking_clerk_secret_key_for_build_67890
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/character/select
      - NEXT_PUBLIC_CLERK_MOCK_MODE=true
      - MONGODB_URI=mongodb://mongodb:27017/game-portal
      - JWT_SECRET=secure_jwt_secret_key
    volumes:
      - nextjs_data:/app/.next/cache
    env_file:
      - ./env/.env.production
    networks:
      - app-network

volumes:
  nextjs_data:
