services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=development
      # Переменные среды для Clerk
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/character/select
      # Другие переменные
      - MONGODB_URI=mongodb://mongodb:27017/game-portal
      - JWT_SECRET=${JWT_SECRET:-development_jwt_secret_replace_in_production}
      - JWT_EXPIRE=30d
    volumes:
      - nextjs_data:/app/.next/cache
      - ./.env.local:/app/.env:ro
    networks:
      - app-network
    depends_on:
      - mongodb
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    # Настройки безопасности
    security_opt:
      - no-new-privileges:true
    # Проверка работоспособности
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB для локальной разработки
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=game-portal
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    # Настройки безопасности
    security_opt:
      - no-new-privileges:true
    # Проверка работоспособности
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/game-portal --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  app-network:
    driver: bridge

volumes:
  nextjs_data:
  mongodb_data: