# Базовый образ
FROM node:18.19.1-alpine

# Рабочая директория
WORKDIR /app

# Добавляем инструменты для диагностики
RUN apk add --no-cache libc6-compat curl

# Копирование только package.json для кэширования зависимостей
COPY package.json package-lock.json ./
RUN npm ci

# Определяем переменные окружения для dev-режима
ENV NODE_ENV=development \
    NEXT_PUBLIC_CLERK_MOCK_MODE=true \
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_dHJ1ZS1nb2xkZmlzaC04MS5jbGVyay5hY2NvdW50cy5kZXYk" \
    CLERK_SECRET_KEY="sk_test_7Wb9VikhkBTuO4O6YUjVVCmxQB5wtAvX8V79kubHMi" \
    MONGODB_URI="mongodb+srv://shoodyakoff:Eta15DTZ0lORouTf@clusterpmgame.kyw9b.mongodb.net/game-portal?retryWrites=true&w=majority&appName=ClusterPmGame" \
    NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in \
    NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up \
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard \
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/character/select \
    NEXT_PUBLIC_CLERK_NO_VERIFICATION=true \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Копирование исходного кода
COPY . .

# Экспортируем порт
EXPOSE 3000

# Запуск в режиме разработки
CMD ["npm", "run", "dev"] 