version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_JA==
      - CLERK_SECRET_KEY=sk_test_valid_key
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/character/select
      - NEXT_PUBLIC_CLERK_MOCK_MODE=true
      - NEXT_PUBLIC_CLERK_NO_VERIFICATION=true
      - PORT=3000
      - HOSTNAME=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./node_modules:/app/node_modules
      - ./.env.local:/app/.env.local

networks:
  default:
    name: gotogrow_network
    driver: bridge

volumes:
  nextjs_data: 