FROM node:18.19.1-alpine AS base

# Установка необходимых зависимостей
RUN apk add --no-cache libc6-compat curl

# Создание рабочей директории
WORKDIR /app

# Копирование собранного приложения
COPY .next ./.next
COPY public ./public
COPY package.json package-lock.json ./
COPY node_modules ./node_modules

# Переменные окружения для времени выполнения (можно переопределить при запуске)
ENV NODE_ENV production
ENV PORT 3000

# Открытие порта
EXPOSE 3000

# Запуск приложения
CMD ["npm", "start"] 