name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 176.124.219.223 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      
      - name: Deploy to server
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          # Копируем исходники на сервер
          ssh deploy@176.124.219.223 "mkdir -p ~/deploy && rm -rf ~/deploy/*"
          scp -r ./* deploy@176.124.219.223:~/deploy/
          
          # Запускаем модифицированный скрипт деплоя на сервере (без git pull)
          ssh deploy@176.124.219.223 "cd ~/deploy && export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY='$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY' && export CLERK_SECRET_KEY='$CLERK_SECRET_KEY' && export MONGODB_URI='$MONGODB_URI' && chmod +x server-setup.sh && ./server-setup.sh" 