name: Deploy to TimeWeb

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 176.124.219.223 >> ~/.ssh/known_hosts
      
      - name: Deploy to TimeWeb
        env:
          SERVER_IP: 176.124.219.223
          SSH_USER: deploy
        run: |
          # Проверка подключения
          ssh $SSH_USER@$SERVER_IP "echo 'Connection successful'"
          
          # Деплой приложения с использованием скрипта обновления
          ssh $SSH_USER@$SERVER_IP << 'ENDSSH'
            cd ~/game
            git pull
            chmod +x update-server.sh
            ./update-server.sh
          ENDSSH 