name: Deploy to TimeWeb

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 176.124.219.223 >> ~/.ssh/known_hosts
      
      - name: Create .env.production with secrets
        run: |
          cat > .env.production << EOF
          # Clerk Authentication
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
          NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
          NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/character/select
          NEXT_PUBLIC_CLERK_MOCK_MODE=true
          NEXT_PUBLIC_CLERK_NO_VERIFICATION=true

          # Настройки приложения
          NODE_ENV=production
          EOF
      
      - name: Deploy to TimeWeb
        env:
          SERVER_IP: 176.124.219.223
          SSH_USER: deploy
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        run: |
          # Проверка подключения
          ssh $SSH_USER@$SERVER_IP "echo 'Connection successful'"
          
          # Создаём рабочий каталог, если он не существует
          ssh $SSH_USER@$SERVER_IP "mkdir -p /home/deploy/game/deploy"
          
          # Копируем весь репозиторий на сервер (включая .git для возможности обновления)
          rsync -avz --exclude 'node_modules' --exclude '.next' . $SSH_USER@$SERVER_IP:/home/deploy/game/deploy/
          
          # Создаем .env файл на сервере с переменными среды
          ssh $SSH_USER@$SERVER_IP "cat > /home/deploy/game/deploy/.env << EOF
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY
          CLERK_SECRET_KEY=$CLERK_SECRET_KEY
          NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
          NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/character/select
          NEXT_PUBLIC_CLERK_MOCK_MODE=true
          NEXT_PUBLIC_CLERK_NO_VERIFICATION=true
          EOF"
          
          # Запускаем сборку и деплой
          ssh $SSH_USER@$SERVER_IP "cd /home/deploy/game/deploy && \
            echo 'Проверка файлов в директории:' && \
            ls -la && \
            echo 'Запуск Docker Compose...' && \
            docker-compose -f docker-compose.prod.yml down && \
            docker-compose -f docker-compose.prod.yml up -d --build"
          
          # Проверяем статус контейнеров
          ssh $SSH_USER@$SERVER_IP "docker ps" 