name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      rebuild:
        description: 'Пересобрать контейнеры?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 176.124.219.223 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      
      - name: Deploy to server
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          REBUILD: ${{ github.event.inputs.rebuild || 'true' }}
        run: |
          # Очищаем и создаем временную директорию для файлов деплоя
          mkdir -p deploy_files
          
          # Копируем только необходимые файлы для сборки
          cp -r src/ deploy_files/
          cp -r public/ deploy_files/
          cp package.json package-lock.json next.config.js fix-clerk-edge.sh Dockerfile docker-compose.prod.yml server-setup.sh deploy_files/
          
          # Копируем только необходимые файлы на сервер
          ssh deploy@176.124.219.223 "mkdir -p ~/deploy && rm -rf ~/deploy/*"
          scp -r deploy_files/* deploy@176.124.219.223:~/deploy/
          
          # Запускаем модифицированный скрипт деплоя на сервере
          ssh deploy@176.124.219.223 "cd ~/deploy && export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY='$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY' && export CLERK_SECRET_KEY='$CLERK_SECRET_KEY' && export MONGODB_URI='$MONGODB_URI' && export REBUILD='$REBUILD' && chmod +x server-setup.sh && chmod +x fix-clerk-edge.sh && ./server-setup.sh" 