name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to server
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SERVER_HOST: ${{ secrets.SSH_HOST }}
          SERVER_USER: ${{ secrets.SSH_USER }}
        run: |
          # Создаем директорию .ssh с нужными правами
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Добавляем хост в известные хосты
          ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
          
          # Копируем исходники на сервер
          ssh $SERVER_USER@$SERVER_HOST "mkdir -p ~/deploy"
          scp -r ./* $SERVER_USER@$SERVER_HOST:~/deploy/
          
          # Запускаем деплой на сервере
          ssh $SERVER_USER@$SERVER_HOST "cd ~/deploy && export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY='$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY' && export CLERK_SECRET_KEY='$CLERK_SECRET_KEY' && export MONGODB_URI='$MONGODB_URI' && ./server-setup.sh" 